included:
  - "CovidWatch iOS"
  - "CovidWatch iOSTests"
  - "CovidWatch iOSUITests"

identifier_name:
  allowed_symbols: "_"
  validates_start_with_lowercase: false
  min_length: 1
  max_length:
    warning: 90
    error: 1000
  excluded:
    - id

opt_in_rules:
  - force_unwrapping

disabled_rules:
  - implicit_getter
  - trailing_whitespace
  - switch_case_alignment
