name: pull_request

on: pull_request

env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:
  xcodebuild:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          gem install bundler:1.16.6
          bundle install
      - name: Xcode Build
        run: |
          bundle exec fastlane build

  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          gem install bundler:1.16.6
          bundle install
      - name: Run Tests
        run: |
          bundle exec fastlane tests
