name: pull_request

on: push

env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:
  xcodebuild:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          gem install bundler:1.16.6
          bundle install
      - name: Xcode Build
        run: |
          bundle exec fastlane build

  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          gem install bundler:1.16.6
          bundle install
          brew install sonar-scanner
      - name: Run Tests
        run: |
          bundle exec fastlane tests
      - name: Run SonarQube
        env:
          PR_BRANCH: github.event.pull_request.head.ref
          SONARCLOUD_LOGIN_KEY: ${{ secrets.SONARCLOUD_LOGIN_KEY }}
        run: |
          bundle exec fastlane ios run_sonar login: $SONARCLOUD_LOGIN_KEY, branch: $PR_BRANCH, key: $PULL_NUMBER
